### ISSUE TITLE
Guided installation fails during package installation

### ISSUE THREAD

**Issue by lenerd** [Torxed/archinstall#61] opened 2020-11-08 16:52 UTC
Hi,

I was testing the guided installer in a virtual machine, but it seems that the installation fails during package installation. I used `pip install archinstall==2.0.6rc11` and `python -m archinstall guided` on the current Arch Linux installation image.

```
Installing packages: ['vim', 'gdb', 'radare2', 'pwndbg', 'tmux']
Error in profile guided: 'list' object has no attribute 'items'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/archinstall/__main__.py", line 65, in run_as_a_module
    exec(profile)  # Is this is very safe?
  File "<string>", line 240, in <module>
  File "/usr/lib/python3.8/site-packages/archinstall/lib/disk.py", line 192, in __exit__
    raise args[1]
  File "<string>", line 240, in <module>
  File "<string>", line 66, in perform_installation
  File "/usr/lib/python3.8/site-packages/archinstall/lib/installer.py", line 78, in __exit__
    raise args[1]
  File "<string>", line 58, in perform_installation
AttributeError: 'list' object has no attribute 'items'
python -m archinstall guided  41.04s user 18.26s system 25% cpu 3:51.50 total
```
Full output [here](https://termbin.com/ygzh).

Edit: When do not select any additional packages, I get the following error:
```
Error in profile guided: 'packages'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/archinstall/__main__.py", line 65, in run_as_a_module
    exec(profile)  # Is this is very safe?
  File "<string>", line 240, in <module>
  File "/usr/lib/python3.8/site-packages/archinstall/lib/disk.py", line 192, in __exit__
    raise args[1]
  File "<string>", line 240, in <module>
  File "<string>", line 66, in perform_installation
  File "/usr/lib/python3.8/site-packages/archinstall/lib/installer.py", line 78, in __exit__
    raise args[1]
  File "<string>", line 52, in perform_installation
KeyError: 'packages'
```

**Comment by Torxed** [comment] 2020-11-08 17:42
Patching! There's an RC out, but it has an issue when selecting a profile.
But if you don't want to install, lets say "awesome" desktop. You can use the release candidate by doing:

    pip install --upgrade archinstall==2.0.6rc11

And that RC *should* work.
Trying to push a proper release by the end of tonight (3h away or so).

**Comment by lenerd** [comment] 2020-11-08 18:16
I am already using version 2.0.6rc11, since I ran into #59 before and saw it has been fixed in the RC.

**Comment by Torxed** [comment] 2020-11-08 18:31
> I am already using version 2.0.6rc11, since I ran into #59 before and saw it has been fixed in the RC.

That is strange, I'll take a look at it right away. Apologies for the inconvenience!

**Comment by lenerd** [comment] 2020-11-08 18:39
Nevermind. Also, I am not in a hurry. :)

**Comment by Torxed** [comment] 2020-11-08 22:07
Will update here with information on the progress, mainly for my own sake so I know what I've done in case I need to jump into other business for a bit.

Commit 5ad6ea2 addresses this slightly, in that the traceback will be more accurate *(will be easier to follow the problem)*.
Will submit a new RC to be able to get the debug output needed, so the new RC won't be a fix but a step in the right direction : )

**Comment by kpcyrd** [comment] 2020-11-08 22:28
I'm not that familiar with pip, but maybe we could generate a package and test-install it with github actions to ensure everything works? I can help with the github actions but need some guidance with python.

**Comment by Torxed** [comment] 2020-11-08 22:33
> I'm not that familiar with pip, but maybe we could generate a package and test-install it with github actions to ensure everything works? I can help with the github actions but need some guidance with python.

I agree, I do have an automated test execution with qemu. I just can't test the last step which is actually booting up the machine (due to EFI variable mismatch). But I've been putting off putting this in to a CI hook because we were discussing potentially transferring this to the official GitLab *(where they have a proper CI-setup with building environments and stuff)* :) But perhaps it's time to do it anyway.

FIY: This issue should be fixed in v2.0.6rc16.
@lenerd: If you don't mind, could you test it with `pip install archinstall==2.0.6rc16` :)

**Comment by lenerd** [comment] 2020-11-09 17:13
@Torxed Just tried it: Everything seems to work now! Thanks for your work on this!

---

Some minor notes that came to my mind:
- Before I saw it is installed by default, I tried to add the `base-devel` group to the additional packages. This gave me an error message "Invalid packages names". Maybe you want to allow to install package groups in the future.
- An option to select the timezone / enable NTP would be nice.
- A simple option to configure networking would also be useful, e.g., enabling DHCP via systemd-networkd.

You have probably already thought about this, but I thought I write it anyway. :)

**Comment by Torxed** [comment] 2020-11-09 17:50
@lenerd Awesome! Just happy to help :)

Regarding your suggestions, one of them is a straight up bug. Something that worked before, but while introducing a package-verification-feature it apparently is a bit strict and prohibits groups .(as the package endpoint won't return hits when searching for package groups)*. So that has to be fixed asap hehe.

The two suggestions have to some extent been in the back of my mind, but I made them formal suggestions and put them as issues here so I don't loose them. I think priority wise I'll make the network configuration happen first, and then I'll jump on the time-zone *(because locales and stuff are iffy business depending on if I want to do automated guessing in the guided profile or not based on locale etc)*.

Again, thanks for verifying that the issue is fixed, I'll go ahead and close this ticket now : )

**Closed by Torxed** 2020-11-09 17:50 UTC
Labels: bug

**Comment by Torxed** [comment] 2020-11-11 21:57
@lenerd Short FYI: network config now added in v2.0.6rc17.
Thanks for suggesting it : )

*(Will release a proper version release once I've squashed #62 and #67)*

**Comment by lenerd** [comment] 2020-11-12 11:36
Great!
I may have to reinstall my VM at some point to checkout the new features. ;)
